version: '3'

services:
  s3:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-minio}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-miniosecretkey}
    command: server /data --console-address ":9001"
    networks:
      - internal
      - public
    volumes:
      - ./data/minio:/data

  gcs:
    image: fsouza/fake-gcs-server
    restart: unless-stopped
    expose:
      - "9100"
    ports:
      - "9100:9100"
    command: ["-scheme", "http", "-port", "9100", "-external-url", "http://0.0.0.0:9100", "-backend", "filesystem"]
    networks:
      - internal
      - public
    volumes:
      - ./data/gcs:/data/cloud-storage

networks:
  internal:
  public:
    driver: bridge
volumes:
  gcs_volume:
  minio_volume:
